# Generated by Django 4.2.4 on 2023-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldslearning',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
