# Generated by Django 4.2.4 on 2023-10-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_modellearning1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modellearning1',
            table='modellearning1-1',
        ),
    ]
