# Generated by Django 4.2.4 on 2023-10-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_alter_modellearning1_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modellearning1',
            table='modellearning1_1',
        ),
    ]
