# Generated by Django 4.2.4 on 2023-10-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0008_alter_modellearning1_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='modellearning2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('choice', models.CharField(choices=[('number', (('1', 'First'), ('2', 'Second'), ('3', 'Third'))), ('string', (('a', 'A'), ('b', 'B'), ('c', 'C')))], default='1', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
