# Generated by Django 4.2.4 on 2023-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0009_modellearning2'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellearning2',
            name='column',
            field=models.CharField(blank=True, db_column='customName', max_length=200, null=True),
        ),
    ]
