# Generated by Django 4.2.4 on 2023-10-29 06:26

import basics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0011_modellearning3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellearning3',
            name='age',
            field=models.IntegerField(validators=[basics.models.age_validator]),
        ),
    ]
