# Generated by Django 4.2.4 on 2023-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_alter_modellearning3_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='timedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique_for_date=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
