# Generated by Django 4.2.4 on 2023-10-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0014_timedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedate',
            name='name',
            field=models.CharField(default='ramu', max_length=200),
        ),
    ]
