# Generated by Django 4.2.4 on 2023-11-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0016_department_alter_timedate_date_alter_timedate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adharnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adhar_no', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='citison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('adharnumber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='basics.adharnumber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
