# Generated by Django 4.2.4 on 2023-11-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0017_adharnumber_citison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adharnumber',
            name='adhar_no',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
