# Generated by Django 4.2.4 on 2023-11-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0021_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
    ]
