# Generated by Django 4.2.4 on 2023-11-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0022_remove_entry_mod_date_remove_entry_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('rationg', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='basics.author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
