# Generated by Django 4.2.4 on 2023-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0023_entry1_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldslearning',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslearning',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
