# Generated by Django 4.2.4 on 2023-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0024_alter_fieldslearning_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldslearning',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
