# Generated by Django 4.2.4 on 2023-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0026_alter_fieldslearning_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldslearning',
            name='personal_number',
            field=models.IntegerField(default=0),
        ),
    ]
