# Generated by Django 4.2.4 on 2023-11-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0027_alter_fieldslearning_personal_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fieldslearning',
            table='fieldsLearning2',
        ),
    ]
