# Generated by Django 4.2.4 on 2023-11-11 15:15

import basics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0028_alter_fieldslearning_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='fieldsLearning1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, validators=[basics.models.EmailValidator])),
                ('phone', models.IntegerField()),
                ('personal_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'fieldsLearning3',
            },
        ),
        migrations.DeleteModel(
            name='fieldsLearning',
        ),
    ]
