# Generated by Django 4.2.4 on 2023-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0029_fieldslearning1_delete_fieldslearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldslearning1',
            name='name',
            field=models.CharField(error_messages={'null': 'Name field is required custom'}, max_length=200),
        ),
    ]
