# Generated by Django 4.2.4 on 2023-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0031_alter_fieldslearning1_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='fieldslearning1',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Name field is required custom'}, max_length=20),
        ),
    ]
