# Generated by Django 4.2.4 on 2023-11-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0032_latest_alter_fieldslearning1_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest',
            old_name='date',
            new_name='date2',
        ),
    ]
