# Generated by Django 4.2.4 on 2023-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0033_rename_date_latest_date2'),
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
            ],
        ),
    ]
