# Generated by Django 4.2.4 on 2023-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0034_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
            ],
        ),
    ]
