# Generated by Django 4.2.4 on 2023-12-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0036_retaildetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='retail',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='retails', to='basics.retaildetails'),
        ),
    ]
