# Generated by Django 4.2.4 on 2023-08-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muru', '0002_color_person_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='Color_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
